config/routes.rb
Rails.application.routes.draw do

	root 'post_images#index'
	get "home/about"

	devise_for :users, :controllers => {
	 :registrations => 'users/registrations',
	 :sessions => 'users/sessions'
	}
	get 'users/top/:id' => 'users#top', as: 'user_infomation'
	resources :users

	resources :carts
	resources :orders

	resources :books do
		resource :book_carts, only: [:create,:destroy]
		resource :post_comments, only: [:create, :destroy]
	end

	resources :post_images, only: [:new, :create, :index, :show]

	# resources :books, only: %w(create)
	# resources :books, only: %w(index create)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

attachment :image
attachment :profile_image
#bookと紐ずけ(1)
has_many :books
has_many :post_comments, dependent: :destroy
has_one :cart
has_many :orders
#ユーザー名は2~20文字とする
validates :name, length: { minimum: 2 }
validates :name, length: { maximum: 20 }
#自己紹介文の長さは最大50文字とする
validates :introduction, length: { maximum: 50 }
#ユーザー名が空欄の場合はエラーメッセージを表示する
validates :name, presence: true
#メールアドレスが空欄の場合はエラーメッセージを表示する
validates :email, presence: true


#電話番号が空欄の場合はエラーメッセージを表示する
validates :mobile, length: { is: 11 }, on: :test
#郵便番号が空欄の場合はエラーメッセージを表示する
validates :zip, length: { is: 7 }, on: :test
#都道府県名が空欄の場合はエラーメッセージを表示する
validates :state, presence: true, on: :test
#市町村名が空欄の場合はエラーメッセージを表示する
validates :city, presence: true, on: :test
#町名以下が空欄の場合はエラーメッセージを表示する
validates :street, presence: true, on: :test
#プロフィール画像が空欄の場合はエラーメッセージを表示する
validates :profile_image, presence: true, on: :test
#introductionが空欄の場合はエラーメッセージを表示する
validates :introduction, presence: true, on: :test
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'not_modal'

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    cart = Cart.new
    cart.user_id = current_user.id
    cart.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
class Users::SessionsController < Devise::SessionsController
  layout 'not_modal'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
layout 'not_modal'
  def index
      #Bookの投稿用
      @users = User.all#kaminariでも表記しているから消せる？
      @book=Book.new
      #kaminari用
      @users = User.page(params[:page]).reverse_order
  end

  def show
      #Bookの投稿用
      @user = User.find(params[:id])
      @book = Book.new
      # binding pry
      #kaminari用
      @books = @user.books.page(params[:page]).reverse_order
  end

  def top
      @user = User.find(params[:id])

  end

  def new
      @user = User.new
  end

  def edit
       @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
      @user.attributes = user_params
      if @user.save(context: :test)
        redirect_to user_path(@user.id)
      else
        render :edit
      end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :zip, :mobile, :state, :city, :street, :birth, :sex, :image_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!--Usersの編集ページ-->
<!--<p>Users#edit</p>
<p>Find me in app/views/users/edit.html.erb</p>
<p>全共通コード(heade)(footer)app/views/layouts/application.html.erb</p>
<p>部分共通コード(left_side)/app/views/books/_list.html.erb</p>-->
<!--住所の補助入力ここから-->
<script>
$(function () {
  $('#zip').jpostal({
    postcode : [
      '#zip'
    ],
    address : {
      '#address' :'%3',
      '#address2'  :'%4',
      '#address3'  :'%5',
    }
  });
});
</script>
<!--住所の補助入力ここから-->
<!--カレンダー表示ここから-->
<script>
  $(function() {
    $("#datepicker").datepicker();
  });
</script>
<!--カレンダー表示ここまで-->
<div class="container">
<p id="notice">
</p>
<div class="row">
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
<ul>
  <% @user.errors.full_messages.each do |message| %>
  <li>
    <%= message %>
  </li>
  <% end %>
</ul>
</div>
<% end %>
<h2>User info</h2>
<div class="field  col-sm-12" style="display:inline-flex">
<P>
<label>Name</label>
<%= f.text_field :name ,class: "col-sm-12"%>
</div>
</p>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>郵便番号</label>
<%= f.text_field :zip, id: "zip" ,class: "col-sm-12" %>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>都道府県</label>
<%= f.text_field :state, id: "address" ,class: "col-sm-12"%>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>市区町村</label>
<%= f.text_field :city, id: "address2" ,class: "col-sm-12"%>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>町名以降</label>
<%= f.text_field :street, id: "address3" ,class: "col-sm-12"%>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>電話番号</label>
<%= f.number_field :mobile ,class: "col-sm-12"%>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>E-Mail</label>
<%= f.email_field :email ,class: "col-sm-12"%>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>生年月日</label>
<%= f.text_field :birth, id: "datepicker" ,class: "col-sm-12" %>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>性別</label>
<%= f.select :sex, [["男","男"],["女","女"],], class: "col-sm-12"%>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>introduction</label>
<%= f.text_area :introduction ,class: "col-sm-12"%>
</div>
</p>
<div class="field col-sm-12" style="display:inline-flex">
<P>
<label>プロフィール画像</label>
<%= f.attachment_field :profile_image ,class: "col-sm-12"%>
</div>
<div class="field col-sm-12" style="display:inline-flex">
<%= f.submit 'Update User' ,class: "col-sm-3 btn btn-primary" %>
</div>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<!--Users全ユーザー一覧-->
<!--<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<p>全共通コード(heade)(footer)app/views/layouts/application.html.erb</p>
<p>部分共通コード(left_side)/app/views/books/_list.html.erb</p>-->
<!--ユーザー一覧-->
<div class="container">
  <p id="notice"></p>
  <div class="row">
    <!--共通項ここから-->
    <!--ユーザ画面-->
    <%= render 'books/list' %>
      <!--共通項ここまで-->
      <!--ユーザー一覧-->
      <div class="col-sm-9">
        <div class="container  col-sm-12">
          <h2>Users</h2>
          <% @users.each do |user| %>
            <div class="users-box row col-sm-4">
              <table class="table-bordered">
                <tbody>
                  <tr>
                    <td colspan="2" rowspan="2">
                      <%= link_to user_infomation_path(user) do %>
                        <%= attachment_image_tag user, :profile_image, :fill, 100, 100,  fallback: "no_image.jpg",class: "img-circle img-thumbnail" %>
                    </td>
                    <% end %>
                      <td colspan="2">名前</td>
                  </tr>
                  <tr>
                    <td colspan="2">
                      <%= user.name %>
                    </td>
                  </tr>
                  <tr>
                    <td colspan="3" rowspan="2"></td>
                    <td>詳細</td>
                  </tr>
                  <tr>
                    <td>
                      <%=link_to "show" , user_path(user.id)%>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <% end %>
              <div class="text-center">
                <%= paginate @users, class: "pagenate" %>
              </div>
        </div>
      </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<!--Users自分が投稿したbooks一覧-->
<!--<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>全共通コード(heade)(footer)app/views/layouts/application.html.erb</p>
<p>部分共通コード(left_side)/app/views/books/_list.html.erb</p>-->
<!--ユーザー一覧-->
<div class="container">
  <p id="notice"></p>
  <div class="row">
    <!--共通項ここから-->
    <!--ユーザ画面-->
    <%= render 'books/list' %>
    <!--共通項ここまで-->
    <!--ユーザー一覧-->
    <div class="col-sm-9">
      <div class="container  col-sm-12">
        <h2>Books</h2>
        <table class="table table-hover">
          <thead>
            <tr>
              <th></th>
              <th>Book Cover</th>
              <th>Date</th>
              <th>Price</th>
              <th>Category</th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_infomation_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,  fallback: "default.jpg"%>
                <% end %>
              </td>
              <td>
                <%= attachment_image_tag book, :image, :fill, 50, 50,  fallback: "default.jpg"%>
              </td>
              <td>
                <%=book.date %>
              </td>
              <td>¥
                <%=book.price %>
              </td>
              <td>
                <%=book.category %>
              </td>
              <td>
                <%=link_to book.title ,book_path(book.id)%>
              </td>
              <td>
                <%=book.opinion %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="text-center">
          <%= paginate @books, class: "pagenate" %>
        </div>
      </div>



    <div class="col-ms-12">
      <h1>購入履歴</h1>
      <% @user.orders.each do |order| %>
        <h2>注文番号：<%= order.id %></h2>
          <% order.book_orders.each do |book_order| %>
            <table class="table table-hover">
              <tbody>
                <tr>
                  <td> <label>商品名</label>
                    <%= book_order.book.title %>
                  </td>
                  <td class="cart_td" colspan="2">  <label>商品カテゴリー</label>
                    <%= book_order.book.category %>
                  </td>
                </tr>
                <tr>
                  <td rowspan="2">
                    <%= attachment_image_tag book_order.book, :image, :fill, 100, 100,  fallback: "default.jpg"%>
                  </td>
                  <td class="cart_td" colspan="2">  <label>商品購入日</label>
                    <%= book_order.created_at %>
                  </td>
                </tr>
                <tr>
                  <td class="cart_td" colspan="2">  <label>値段</label>
                    <%= book_order.book.price %>円</td>
                </tr>
              </tbody>
            </table>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<!--Usersのユーザー登録情報ページ
Find me in app/views/users/top.html.erb
全共通コード(heade)(footer)app/views/layouts/application.html.erb-->


<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h1>USER DATA </h1>
      <div class="user-date2">
        <div class="user-image text-center">
          <%= attachment_image_tag @user, :profile_image, :fill, 250, 250,  fallback: "no_image_top.jpg",class: "img-circle img-thumbnail img-responsive center-block" %>
          <h1>
            <%= @user.name %>
          </h1>
        </div>
        <div class="user-blocks text-center">
          <div class="container-icon">
            <%= link_to 'https://www.facebook.com/' do %>
            <i class="facebook fa fa-facebook-square target" style="font-size:100px"></i>
            <% end %>
          </div>&emsp;&emsp;&emsp; 
          <div class="container-icon">
            <%= link_to 'https://twitter.com/' do %>
            <i class="twitter fa fa-twitter-square target" style="font-size:100px"></i>
            <% end %>
          </div>&emsp;&emsp;&emsp; 
          <div class="container-icon">
            <%= link_to 'https://www.instagram.com/', class: "insta_btn" do %>
            <span class="insta target">
              <i class="instagram fa fa-instagram target" style="font-size:100px"></i>
            </span>
            <% end %>
          </div>
          <table>
            <tbody class="row">
              <div class="col-sm-10 col-sm-offset-1">
                <tr>
                  <td colspan="2">
                    <%= link_to user_path(@user.id) do %>
                    <i class="btn btn-default  glyphicon glyphicon-book col-sm-10 col-sm-offset-1">
                      <h2>
                        <strong>投稿BOOK一覧 </strong>
                      </h2>
                    </i>
                    <% end %>
                  </td>
                </tr>
                <tr class="col-sm-10 col-sm-offset-1 user-border">
                  <td>ユーザーネーム： </td>
                  <td>
                    <%= @user.name %>
                  </td>
                </tr>
                <tr class="col-sm-10 col-sm-offset-1 user-border">
                  <td>生年月日： </td>
                  <td>
                    <%= @user.birth %>
                  </td>
                </tr>
                <tr class="col-sm-10 col-sm-offset-1 user-border">
                  <td>性別： </td>
                  <td>
                    <%= @user.sex %>
                  </td>
                </tr>
                <tr class="col-sm-10 col-sm-offset-1 user-border">
                  <td>電話番号： </td>
                  <td>
                    <%= @user.mobile %>
                  </td>
                </tr>
                <tr class="col-sm-10 col-sm-offset-1 user-border">
                  <td>メールアドレス： </td>
                  <td>
                    <%= @user.email %>
                  </td>
                </tr>
                <tr class="col-sm-10 col-sm-offset-1 user-border">
                  <td>郵便番号： </td>
                  <td>
                    <%= @user.zip %>
                  </td>
                </tr>
                <tr class="col-sm-10 col-sm-offset-1 user-border">
                  <td>住所： </td>
                  <td id="address_image">
                    <%= @user.state %>
                    <%= @user.city %>
                    <%= @user.street %>
                  </td>
                </tr>
                <tr class="col-sm-10 col-sm-offset-1 user-border">
                  <td colspan="2">地図画像 </td>
                </tr>
                <tr>
                  <td>
                <div id="map-canvas"></div>
                  </td>
                </tr>
              </div>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

   <script async defer
   src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyDPVe7UmmoFRGDayibTbqQYWeU4_0cJBPM&callback=initMap">
 </script>