config/routes.rb
Rails.application.routes.draw do

	root 'post_images#index'
	get "home/about"

	devise_for :users, :controllers => {
	 :registrations => 'users/registrations',
	 :sessions => 'users/sessions'
	}
	get 'users/top/:id' => 'users#top', as: 'user_infomation'
	resources :users

	resources :carts
	resources :orders

	resources :books do
		resource :book_carts, only: [:create,:destroy]
		resource :post_comments, only: [:create, :destroy]
	end

	resources :post_images, only: [:new, :create, :index, :show]

	# resources :books, only: %w(create)
	# resources :books, only: %w(index create)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

#投稿日が空欄の場合はエラーメッセージを表示する
validates :date, presence: true
#投稿時のタイトル必須
validates :title, presence: true
#投稿時の本文必須
validates :opinion, presence: true
#投稿本文の長さは最大200文字とする
validates :opinion, length: { maximum: 200 }
#priceが1000以上でなければならない
validates :price, :numericality => { :greater_than_or_equal_to => 1000 }
#画像が必須
validates :image, presence: true

attachment :image
#Userと紐ずけ(N)
belongs_to :user
has_one :stock

has_many :book_carts, :dependent => :destroy
has_many :book_orders
has_many :post_comments, dependent: :destroy

end

app/models/book_cart.rb
class BookCart < ApplicationRecord
	belongs_to :book
	belongs_to :cart
end

app/models/book_order.rb
class BookOrder < ApplicationRecord
	belongs_to :book
	belongs_to :order
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :book_carts, :dependent => :destroy
	belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :book_orders , :dependent => :destroy
	belongs_to :user
end

app/models/post_comment.rb
class PostComment < ApplicationRecord


#コメント必須
validates :comment, presence: true

belongs_to :user
belongs_to :book
end

app/models/stock.rb
class Stock < ApplicationRecord
	has_one :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

attachment :image
attachment :profile_image
#bookと紐ずけ(1)
has_many :books
has_many :post_comments, dependent: :destroy
has_one :cart
has_many :orders
#ユーザー名は2~20文字とする
validates :name, length: { minimum: 2 }
validates :name, length: { maximum: 20 }
#自己紹介文の長さは最大50文字とする
validates :introduction, length: { maximum: 50 }
#ユーザー名が空欄の場合はエラーメッセージを表示する
validates :name, presence: true
#メールアドレスが空欄の場合はエラーメッセージを表示する
validates :email, presence: true


#電話番号が空欄の場合はエラーメッセージを表示する
validates :mobile, length: { is: 11 }, on: :test
#郵便番号が空欄の場合はエラーメッセージを表示する
validates :zip, length: { is: 7 }, on: :test
#都道府県名が空欄の場合はエラーメッセージを表示する
validates :state, presence: true, on: :test
#市町村名が空欄の場合はエラーメッセージを表示する
validates :city, presence: true, on: :test
#町名以下が空欄の場合はエラーメッセージを表示する
validates :street, presence: true, on: :test
#プロフィール画像が空欄の場合はエラーメッセージを表示する
validates :profile_image, presence: true, on: :test
#introductionが空欄の場合はエラーメッセージを表示する
validates :introduction, presence: true, on: :test
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
layout 'not_modal'
  def index
      @books = Book.all
      @books = Book.page(params[:page]).reverse_order
      # binding.pry
      @book = Book.new
      #ransack用
      @q = Book.ransack(params[:q])
      @books = @q.result.page(params[:page])
  end

  def show
      @book = Book.new
      #コメント投稿用
      @bookc = Book.find(params[:id])
      @post_comment = PostComment.new
      @post_comments = @bookc.post_comments.page(params[:page]).reverse_order
 end


  def new
      @book=Book.new
  end


  def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
        redirect_to book_path(@book.id)
      else
        @books = Book.page(params[:page]).reverse_order
        @q = Book.ransack(params[:q])
        render :index
      end
  end


  def edit
        @book = Book.find(params[:id])
  end

  def update
        @book = Book.find(params[:id])
        @book.update(book_params)
        redirect_to book_path(@book.id)
  end

  def destroy
        @book=Book.find(params[:id])
        @book.destroy
        redirect_to books_path
  end


  private
  def book_params
    params.require(:book).permit(:title, :opinion, :user_id, :category, :date, :image, :price, :quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!
layout 'not_modal'
def show
# binding pry

end

def create

end

   private
    def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout 'not_modal'
def home
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :authenticate_user!
 layout 'not_modal'

  def pay
      Payjp.api_key = 'sk_test_b41540fd792cd864c8590f70'
      charge = Payjp::Charge.create(
      :amount => 3500,
      :card => params['payjp-token'],
      :currency => 'jpy',
      )
      redirect_to root_path
  end

  # def show
  #     @book_orders = BookOrder.find(book_order_params[:id])
  # end

  def new
     @order = Order.new
  end

  def create
        #オーダー保存
        @order = Order.new(order_params)
        @order.user_id = current_user.id
        # if オーダーが保存できたら
        if @order.save
        # book_cartsを持ってくる。（アソシエーションでuserから頑張る）
        book_carts = current_user.cart.book_carts

        book_carts.each do |book_cart|
          
          book_order = BookOrder.new

          book_order.book_id = book_cart.book_id
          book_order.order_id = @order.id
        
          book_order.save
          # book_cartは処理が終わったら削除
          book_cart.destroy
        end
      end
      redirect_to root_path
  end




  private
    def order_params
    params.require(:order).permit(:name , :mobile , :user_id, :price, :quantity, :zip, :state, :city, :street,:freight, :shipping_method, :phone_number, :email)
    end

    # def ブックオーダーのストロングパラメータ
    def book_order_params
      params.require(:book_order).permit(:book_id, :order_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
layout 'not_modal'
  def index
      #Bookの投稿用
      @users = User.all#kaminariでも表記しているから消せる？
      @book=Book.new
      #kaminari用
      @users = User.page(params[:page]).reverse_order
  end

  def show
      #Bookの投稿用
      @user = User.find(params[:id])
      @book = Book.new
      # binding pry
      #kaminari用
      @books = @user.books.page(params[:page]).reverse_order
  end

  def top
      @user = User.find(params[:id])

  end

  def new
      @user = User.new
  end

  def edit
       @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
      @user.attributes = user_params
      if @user.save(context: :test)
        redirect_to user_path(@user.id)
      else
        render :edit
      end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :zip, :mobile, :state, :city, :street, :birth, :sex, :image_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
	:user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/book_carts_helper.rb
module BookCartsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!--<p>Find me in app/views/books/_list.html.erb</p>
<p>部分共通コード(left_side)/app/views/books/_list.html.erb</p>-->
<!--共通のコード-->
<!--カレンダーの表示ここから-->
<script>
  $(function() {
    $("#datepicker").datepicker();
  });
</script>
<!--カレンダーの表示ここまで-->
<div class="col-sm-3">
  <div class="container col-sm-12">
    <h2>User info </h2>
    <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, class: "profile-thumb", fallback: "no_image.jpg" , class: "img-circle img-thumbnail" %>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
          <th>name </th>
          <th>
            <%= current_user.name %>
          </th>
        </tr>
        <tr>
          <th>introduction </th>
          <th>
            <%= current_user.introduction %>
          </th>
        </tr>
      </tbody>
    </table>
    <div class="field row">
      <%= link_to edit_user_path(current_user) do %>
      <i class="btn btn-default  glyphicon glyphicon-wrench col-sm-12"></i>
      <% end %>
    </div>
    <!--New book投稿フォーム-->
    <h2>New book </h2>
    <%= form_for(@book) do |f| %>
    <!--バリデーションメッセージ-->
    <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <!--バリデーションメッセージ-->
    <div class="field row">
      <label>BOOK COVER </label>
      <%= f.attachment_field :image %>
    </div>
    <div class="field row">
      <label>投稿日 </label>
      <%= f.text_field :date, id: "datepicker" ,class: "col-sm-12" %>
    </div>
    <div class="field row">
      <label>Price </label>
      <%= f.number_field :price,min: 0,step: 100, class: "col-sm-12"%>
    </div>
    <div class="field row">
      <label>Category </label>
      <%= f.select :category, [["小説","小説"],["漫画","漫画"],["自伝","自伝"],
      ["雑誌","雑誌"], ["サスペンス","サスペンス"],] ,class: "col-sm-12 select-category" %>
    </div>
    <div class="field row">
      <label>Title </label>
      <%= f.text_field :title, class: "col-sm-12"%>
    </div>
     <div class="field row">
      <label>個数</label>
      <%= f.number_field :quantity, min: 0,class: "col-sm-12"%>
    </div>
    <div class="field row">
      <label>Opinion </label>
      <%= f.text_area :opinion, class: " col-sm-12" %>
    </div>
    <div class="actions row">
      <%= f.submit "Create Book", class:"btn btn btn-primary col-sm-12" %>
    </div>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<!--Booksのの編集ページ-->
<!--<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>-->
<div class="container">
  <p id="notice"></p>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2>Editing Book</h2>
      <%= form_for (@book) do |f| %>
      <div class="field row">
        <p>
          <label>Category</label>
        </p>
        <%= f.select :category, [["小説","小説"],["漫画","漫画"],["自伝","自伝"],
           ["雑誌","雑誌"], ["サスペンス","サスペンス"],],class: "col-sm-12"%>
      </div>
      <div class="field row">
        <label>Title</label>
        <%= f.text_field :title, class: " col-sm-12"%>
      </div>
      <div class="field row">
        <label>Opinion</label>
        <%= f.text_area :opinion, class: " col-sm-12" %>
      </div>
      <div class="field row">
        <%= button_tag :type => "submit", :class =>"btn btn-primary col-xs-12" do %>Update Book 
        <% end %>
      </div>
      <%=link_to "Show", book_path(@book.id) %>| 
      <%=link_to "Back", books_path%>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<!--books全ユーザーの投稿一覧-->
<!--<h1>books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>
<p>全共通コード(heade)(footer)app/views/layouts/application.html.erb</p>
<p>部分共通コード(left_side)/app/views/books/_list.html.erb</p>-->
<!--ユーザー一覧-->
<div class="container">
  <p id="notice"></p>
  <div class="row">
    <div class="navbar navbar-static-top navbar-right">
      <!-- navbar-brand -->
      <%= link_to 'Book検索', books_path, class: 'navbar-brand' %>
      <!-- navbar-form  フォーム（form要素）を配置すること-->
      <!-- navbar-left メニュー項目、フォーム、テキストなどは、左寄せにする-->
      <%= search_form_for @q, html: { class: 'navbar-form navbar-left' } do |form| %>
      <!--Bootstrapでのformの作る時 form-group  text系はlabelと一緒に<div class="form-group">で囲む-->
      <div class="form-group">
        <!--ootstrapでのformの作る時 form-control text系はclass="form-control"を定義-->
        <%= form.search_field :title_or_price_eq, class: 'form-control', placeholder: 'Title_or_Price(完全一致)' %>
      </div>
      <%= form.submit class: 'btn btn-default' %>並べ替え：
      <%= sort_link(@q, :title, 'タイトル', default_order: :desc ,class: "navbar-brand") %>
      <%= sort_link(@q, :category, 'カテゴリー', default_order: :desc ,class: "navbar-brand") %>
      <%= sort_link(@q, :price, '値段', default_order: :desc ,class: "navbar-brand") %>
      <% end %>
    </div>
    <!--共通項ここから-->
    <!--ユーザ画面-->
    <!--部分テンプレートに変数を渡す場合-->
    <!--,locals: { book: @book }-->
    <%= render 'books/list' %>
    <!--共通項ここまで-->
    <!--ユーザー一覧-->
    <div class="col-sm-9">
      <div class="container">
        <h2>Books</h2>
        <% @books.each do |book| %>
        <div class="books-box row col-sm-3">
          <table class="table-bordered table table-hover text-left col-sm-3">
            <tbody>
              <tr>
                <td>
                  <%= attachment_image_tag book, :image, :fill, 100, 100,  fallback: "default.jpg"%>
                </td>
                <td>
                  <%= link_to book.title ,book_path(book.id)%><br>

                 <%= link_to "購入", book_book_carts_path(book.id),method: :post, class: "btn btn-danger" %>
                </td>
              </tr>

              <tr>
                <td>Price</td>
                <td>¥
                  <%=book.price %>
                </td>
              </tr>

              <tr>
                <td>Category</td>
                <td>
                  <%=book.category %>
                </td>
              </tr>

              <tr>
                <td>Opinion</td>
                <td>
                  <%=book.opinion %>
                </td>
              </tr>

              <tr>
                <td>在庫数</td>
                <td>
                  <%=book.quantity %>
                </td>
              </tr>

              <tr>
                <td>投稿日 
                  <br>
                  <%=book.date%>
                </td>
                <td>
                  <%= link_to book.user do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,  fallback: "default.jpg" , class: "img-circle"%>
                  <br>
                  <%= book.user.name %>
                  <% end %>
                </td>
              </tr>

            </tbody>
          </table>
        </div>
        <% end %>
      </div>
      <div class="text-center">
        <%= paginate @books, class: "pagenate" %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<!--投稿後のBOOKの詳細ページ-->
<!--<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>
<p>全共通コード(heade)(footer)app/views/layouts/application.html.erb</p>
<p>部分共通コード(left_side)/app/views/books/_list.html.erb</p>-->
<head>
  <script>
    $(function() {
        $("#datepicker").datepicker();
      });
  </script>
</head>
<!--ユーザー一覧-->
<div class="container">
  <p id="notice">
  </p>
  <div class="row">
    <!--ここから部分共通部分-->
    <div class="col-sm-3">
      <div class="container col-sm-12">
        <h2>User info</h2>
        <%= attachment_image_tag @bookc.user, :profile_image, :fill, 100, 100, class: "profile-thumb", fallback: "no_image.jpg" , class: "img-circle"%>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th>
                <%= @bookc.user.name %>
              </th>
            </tr>
            <tr>
              <th>introduction</th>
              <th>
                <%= @bookc.user.introduction %>
              </th>
            </tr>
          </tbody>
        </table>
        <div class="field row">
          <%= link_to edit_user_path(current_user) do %>
          <i class="btn btn-default  glyphicon glyphicon-wrench col-sm-12"></i>
          <% end %>
        </div>
        <!--New book投稿フォーム-->
        <h2>New book</h2>
        <%= form_for(@book) do |f| %>
        <% if @book.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="field row">
          <label>BOOK COVER</label>
          <%= f.attachment_field :image %>
        </div>
        <div class="field row">
          <label>投稿日</label>
          <%= f.text_field :date, id: "datepicker" ,class: "col-sm-12" %>
        </div>
        <div class="field row">
          <label>Price</label>
          <%= f.number_field :price,min: 0,step: 100, class: "col-sm-12"%>
        </div>
        <div class="field row">
          <label>Category</label>
          <%= f.select :category, [["小説","小説"],["漫画","漫画"],["自伝","自伝"],
      ["雑誌","雑誌"], ["サスペンス","サスペンス"],],class: "col-sm-12"%>
        </div>
        <div class="field row">
          <label>Title</label>
          <%= f.text_field :title, class: " col-sm-12"%>
        </div>
        <div class="field row">
          <label>Opinion</label>
          <%= f.text_area :opinion, class: " col-sm-12" %>
        </div>
        <div class="field row">
          <label>個数</label>
          <%= f.number_field :quantity, min: 0,class: "col-sm-12"%>
        </div>
        <div class="actions row">
          <%= f.submit "Create Book", class:"btn btn btn-primary col-sm-12" %>
        </div>
        <% end %>
      </div>
    </div>
    <!--ここまで部分共通部分-->
    <!--ユーザー一覧-->
    <div class="col-sm-9">
      <div class="container  col-sm-12">
        <h2>Book detail</h2>
        <table class="table">
          <thead>
            <tr>
              <th>Profile imaga</th>
              <th>Book Cover</th>
              <th>Date</th>
              <th>Price</th>
              <th>Category</th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= link_to @bookc.user do %>
                <%= attachment_image_tag @bookc.user, :profile_image, :fill, 100, 100,  fallback: "default.jpg" %>
                <br>
                <%= @bookc.user.name %>
                <% end %>
              </td>
              <td>
                <%= attachment_image_tag @bookc, :image, :fill, 100, 100,  fallback: "no_image.jpg"%>
              </td>
              <td>
                <%= @bookc.date %>
              </td>
              <td>¥
                <%= @bookc.price %>
              </td>
              <td>
                <%= @bookc.category %>
              </td>
              <td>
                <%= link_to @bookc.title %>
              </td>
              <td>
                <%= @bookc.opinion %>
              </td>
              <td>
                <% if @bookc.user == current_user %>
                <%=link_to "Edit", edit_book_path(@bookc.id), class: "btn-sm btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @bookc.user == current_user %>
                <%= link_to "Destroy", book_path(@bookc), method: :delete, class: "btn-sm btn-danger", data: { confirm: '本当に消しますか?'} %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <!--コメント機能-->
      <div class="comment-list bt style-2" id="comments">
        <div class="float-wrapper">
          <h2 class="comment-count">
            <%= @bookc.post_comments.count %>件コメント 
          </h2>
        </div>
        <ol>
        <% @post_comments.each do |post_comment| %>
        <div class="balloon1">
          <div class="icon">
            <%= attachment_image_tag post_comment.user,:profile_image, :fill, 100, 100, fallback: "no_image.jpg" , class: "img-circle" %>
          </div>
          <table>
            <tbody>
              <tr>
                <td class="text-right">名前：</td>
                <td>
                  <%= post_comment.user.name %>
                </td>
              </tr>
              <tr>
                <td class="text-right">投稿日：</td>
                <td>
                  <%= post_comment.created_at.strftime('%Y/%m/%d') %>
                </td>
              </tr>
              <tr>
                <td class="text-right">コメント：</td>
                <td>
                  <%= post_comment.comment %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>
        <% end %>
        <!--ページング機能-->
        <div class="text-center">
          <%= paginate @post_comments, class: "pagenate" %>
        </div>
        <hr>
        <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
          <h3 class="section-title left">
            <span>コメント</span>
          </h3>
        </div>
        <!--コメント送信部分-->
        <%= form_for [@bookc, @post_comment] do |f| %>
        <!--エラーメッセージ表示機能-->
        <% if flash[:error].present? %>
        <ul class="errors">
          <% flash[:error].each do |e| %>
          <li>
            <%= e %>
          </li>
          <% end %>
        </ul>
        <% end %>
        <div class="row">
          <div class="col-sm-12">
            <%= f.text_field :comment, class: "form-control",placeholder: "コメントをここに" %>
          </div>
        </div>
        <%= f.submit "送信する", class: "btn btn-primary pull-right" %>
        <% end %>
        <!--コメント機能-->
      </div>
    </div>
  </div>
</div>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<!-- <h1>Carts#index</h1>
<p>Find me in app/views/carts/index.html.erb</p>
 -->

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<!-- <h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>
 -->

<div class="container">
	<div class="row">
		<div class="col-ms-12" style="background-color: #FFF;">
		  <p id="notice"></p>
		  <h1>カート</h1>
			<table class="table table-hover">
				<tbody>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td><label>価格</label></td>
						<td><label>数量</label></td>
					</tr>
					<% current_user.cart.book_carts.each do |book_cart| %>
					<tr>
						<td rowspan="3"><%= attachment_image_tag book_cart.book, :image, :fill, 100, 100,  fallback: "default.jpg"%></td>
						<td colspan="2"><label>タイトル</label></td>
						<td colspan="2"><%= book_cart.book.title %></td>
						<td rowspan="2">¥<%= book_cart.book.price %></td>
						<td rowspan="2"><%= book_cart.book.quantity %>個</td>
					</tr>
					<tr>
						<td colspan="2"><label>出品者</label></td>
						<td colspan="2"><%= book_cart.book.user.name %></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td><%= link_to "Destroy", book_book_carts_path(book_cart.book_id, book_cart.id), method: :delete, class: "btn-sm btn-danger", data: { confirm: '本当に消しますか?'} %></td>
						<td><%=link_to "詳細", book_path(book_cart.book.id), class: "btn-sm btn-info"%></td>
						<td></td>
						<td></td>
					</tr>

					<% end %>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td><label>合計金額</label> <%= @total_price %></td>
						<td><%=link_to "戻る", books_path %></td>
						<td><%=link_to "購入", new_order_path %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<!-- <h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>
 -->

<div class="container">
	<div class="row">
		<div class="col-ms-12" style="background-color: orange;">
		<p id="notice"></p>
		<h1>購入確認画面</h1>
		 <%= form_for @order do |f| %>
			<table>
				<tbody>
					<tr>
						<td>名前：</td>
						<td><%= f.text_field :name, :value => current_user.name %></td>
					</tr>
					<tr>
						<td>郵便番号：</td>
						<td><%= f.text_field :zip, :value => current_user.zip %></td>
					</tr>
					<tr>
						<td>都道府県：</td>
						<td><%= f.text_field :state, :value => current_user.state %></td>
					</tr>
					<tr>
						<td>市町村：</td>
						<td><%= f.text_field :city, :value => current_user.city %></td>
					</tr>
					<tr>
						<td>町名以下：</td>
						<td><%= f.text_field :street, :value => current_user.street %></td>
					</tr>
					<tr>
						<td>電話番号：</td>
						<td><%= f.text_field :mobile, :value => current_user.mobile %></td>
					</tr>
					<tr>
						<td>メールアドレス：</td>
						<td><%= f.text_field :email, :value => current_user.email %></td>
					</tr>
					<tr>
						<td>合計：</td>
						<td></td>
					</tr>
					<tr>
						<td>配送方法：</td>
						<td><%= f.select :shipping_method, [["手渡し", 0],["船", 1]] %></td>
					</tr>
					<tr>
						<td>送料：</td>
						<td><%= f.select :freight, [[1000, 1000]] %></td>
					</tr>
					<tr>
						<td>合計：</td>
						<td></td>
					</tr>
					<tr>
						<td>戻るボタン</td>
						<td><%= f.submit "購入" %></td>
						<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>	

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>