config/routes.rb
Rails.application.routes.draw do

	root 'post_images#index'
	get "home/about"

	devise_for :users, :controllers => {
	 :registrations => 'users/registrations',
	 :sessions => 'users/sessions'
	}
	get 'users/top/:id' => 'users#top', as: 'user_infomation'
	resources :users

	resources :carts
	resources :orders

	resources :books do
		resource :book_carts, only: [:create,:destroy]
		resource :post_comments, only: [:create, :destroy]
	end

	resources :post_images, only: [:new, :create, :index, :show]

	# resources :books, only: %w(create)
	# resources :books, only: %w(index create)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

#投稿日が空欄の場合はエラーメッセージを表示する
validates :date, presence: true
#投稿時のタイトル必須
validates :title, presence: true
#投稿時の本文必須
validates :opinion, presence: true
#投稿本文の長さは最大200文字とする
validates :opinion, length: { maximum: 200 }
#priceが1000以上でなければならない
validates :price, :numericality => { :greater_than_or_equal_to => 1000 }
#画像が必須
validates :image, presence: true

attachment :image
#Userと紐ずけ(N)
belongs_to :user
has_one :stock

has_many :book_carts, :dependent => :destroy
has_many :book_orders
has_many :post_comments, dependent: :destroy

end

app/models/book_cart.rb
class BookCart < ApplicationRecord
	belongs_to :book
	belongs_to :cart
end

app/models/book_order.rb
class BookOrder < ApplicationRecord
	belongs_to :book
	belongs_to :order
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :book_carts, :dependent => :destroy
	belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :book_orders , :dependent => :destroy
	belongs_to :user
end

app/models/post_comment.rb
class PostComment < ApplicationRecord


#コメント必須
validates :comment, presence: true

belongs_to :user
belongs_to :book
end

app/models/stock.rb
class Stock < ApplicationRecord
	has_one :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

attachment :image
attachment :profile_image
#bookと紐ずけ(1)
has_many :books
has_many :post_comments, dependent: :destroy
has_one :cart
has_many :orders
#ユーザー名は2~20文字とする
validates :name, length: { minimum: 2 }
validates :name, length: { maximum: 20 }
#自己紹介文の長さは最大50文字とする
validates :introduction, length: { maximum: 50 }
#ユーザー名が空欄の場合はエラーメッセージを表示する
validates :name, presence: true
#メールアドレスが空欄の場合はエラーメッセージを表示する
validates :email, presence: true


#電話番号が空欄の場合はエラーメッセージを表示する
validates :mobile, length: { is: 11 }, on: :test
#郵便番号が空欄の場合はエラーメッセージを表示する
validates :zip, length: { is: 7 }, on: :test
#都道府県名が空欄の場合はエラーメッセージを表示する
validates :state, presence: true, on: :test
#市町村名が空欄の場合はエラーメッセージを表示する
validates :city, presence: true, on: :test
#町名以下が空欄の場合はエラーメッセージを表示する
validates :street, presence: true, on: :test
#プロフィール画像が空欄の場合はエラーメッセージを表示する
validates :profile_image, presence: true, on: :test
#introductionが空欄の場合はエラーメッセージを表示する
validates :introduction, presence: true, on: :test
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
layout 'not_modal'
  def index
      @books = Book.all
      @books = Book.page(params[:page]).reverse_order
      # binding.pry
      @book = Book.new
      #ransack用
      @q = Book.ransack(params[:q])
      @books = @q.result.page(params[:page])
  end

  def show
      @book = Book.new
      #コメント投稿用
      @bookc = Book.find(params[:id])
      @post_comment = PostComment.new
      @post_comments = @bookc.post_comments.page(params[:page]).reverse_order
 end


  def new
      @book=Book.new
  end


  def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
        redirect_to book_path(@book.id)
      else
        @books = Book.page(params[:page]).reverse_order
        @q = Book.ransack(params[:q])
        render :index
      end
  end


  def edit
        @book = Book.find(params[:id])
  end

  def update
        @book = Book.find(params[:id])
        @book.update(book_params)
        redirect_to book_path(@book.id)
  end

  def destroy
        @book=Book.find(params[:id])
        @book.destroy
        redirect_to books_path
  end


  private
  def book_params
    params.require(:book).permit(:title, :opinion, :user_id, :category, :date, :image, :price, :quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!
layout 'not_modal'
def show
# binding pry

end

def create

end

   private
    def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout 'not_modal'
def home
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
	:user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/book_carts_helper.rb
module BookCartsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!--共通のコード-->
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--jsファイルここから-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--モーダル表示-->
    <!--<script src="js/modal.js"></script>-->
    <!--アコーディオン表示-->
    <!--<script src="accordion.js"></script>-->
    <!--jsファイルここまで-->
    <!--font type-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!--カレンダー-->
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js">
    </script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js">
    </script>
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/redmond/jquery-ui.css" rel="stylesheet">
  </head>




<body class='<%= "#{controller.controller_name}" %>'>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span class="glyphicon glyphicon-book">Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <%if user_signed_in? %>
            <!--ログイン中のヘッダー-->
            <li>
              <%= link_to user_path(current_user.id), :method => :GET do %>
              <i class="glyphicon glyphicon-home"></i>Home
              <% end %>
              <!--<a class="glyphicon glyphicon-home" href="/users"> Home</a>-->
            </li>
            <li>
              <%= link_to users_path, :method => :GET do %>
              <i class="glyphicon glyphicon-user"></i>Users
              <% end %>
              <!--<a class="glyphicon glyphicon-user" href="/users"> Users</a>-->
            </li>
            <li>
              <%= link_to books_path, :method => :GET do %>
              <i class="glyphicon glyphicon-book"></i>Books
              <% end %>
              <!--<a class="glyphicon glyphicon-book" href="/books"> Books</a>-->
            </li>
              <li>
              <%= link_to cart_path(current_user.cart.id),:method => :GET do %>
              <i class="glyphicon glyphicon-shopping-cart"></i>Cart
              <% end %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, :method => :delete do %>
              <i class="glyphicon glyphicon-log-out"></i>Logout
              <% end %>
            </li>


            <% else %>
            <!--ログアウト中のヘッダー-->
            <li>
              <%= link_to root_path, :method => :GET do %>
              <i class="glyphicon glyphicon-home"></i>Home
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path, :method => :GET do %>
              <i class="glyphicon glyphicon-link"></i>About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, :method => :GET do %>
              <i class="glyphicon glyphicon-edit"></i>Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, :method => :GET do %>
              <i class="glyphicon glyphicon-log-in"></i>Login
              <% end %>
            </li>
            <li>
              <button class="btn btn-link button-link glyphicon glyphicon-user" id="modal-open" type="button">Signup|Login</button>
            </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="footer text-center">
            <p>CopyRight HAYATO</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/not_modal.html.erb
<!--共通のコード-->
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <!--font type-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!--カレンダー-->
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/redmond/jquery-ui.css">

  </head>
<body class='<%= "#{controller.controller_name}" %>'>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span class="glyphicon glyphicon-book">Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <!--ログイン中のヘッダー-->
            <li>
              <%= link_to user_path(current_user.id), :method => :GET do %>
              <i class="glyphicon glyphicon-home"></i>Home
              <% end %>
              <!--<a class="glyphicon glyphicon-home" href="/users"> Home</a>-->
            </li>
            <li>
              <%= link_to users_path, :method => :GET do %>
              <i class="glyphicon glyphicon-user"></i>Users
              <% end %>
              <!--<a class="glyphicon glyphicon-user" href="/users"> Users</a>-->
            </li>
            <li>
              <%= link_to books_path, :method => :GET do %>
              <i class="glyphicon glyphicon-book"></i>Books
              <% end %>
              <!--<a class="glyphicon glyphicon-book" href="/books"> Books</a>-->
            </li>
               <li>
              <%= link_to cart_path(current_user.cart.id), :method => :GET do %>
              <i class="glyphicon glyphicon-shopping-cart"></i>Cart
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, :method => :delete do %>
              <i class="glyphicon glyphicon-log-out"></i>Logout
              <% end %>
            </li>
            <% else %>
            <!--ログアウト中のヘッダー-->
            <li>
              <%= link_to root_path, :method => :GET do %>
              <i class="glyphicon glyphicon-home"></i>Home
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path, :method => :GET do %>
              <i class="glyphicon glyphicon-link"></i>About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, :method => :GET do %>
              <i class="glyphicon glyphicon-edit"></i>Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, :method => :GET do %>
              <i class="glyphicon glyphicon-log-in"></i>Login
              <% end %>
            </li>
            <li>
              <button type="button " class="btn btn-link button-link glyphicon glyphicon-user">Signup|Login </button>
            </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="footer text-center">
            <p>CopyRight HAYATO</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>